### ISSUE TITLE
docker image size increases significantly during patching in the update option

### ISSUE THREAD

**Issue by skommala** [oracle/weblogic-image-tool#111]
We don't see any significant increase in docker image size with create command even after lot of patches are applied. But there is significant increase in docker image size with the update command even with single patch. Its almost 1GB increase. This is a major blocker for us as we update our images very often.

**Comment by mriccell** [comment]
When you invoke the update option you are extending an image to either patch, change a domain configuration, apply a new application.  Any update are new Docker layers on top of the base image and thus the size increase.  If you want to keep the image size as small as possible create option should be used instead of update.  
We would like to understand the 1GB increase, could you provide more information for us to do the analysis?  We need to know what you are updating and what is the base image you are starting with and the size.

**Comment by ddsharpe** [comment]
This behavior is expected, as this is the way that Docker works.  Using update to apply patches should be done only when absolutely necessary.  The create image process allows us to workaround this Docker behavior since we are starting from a known point.  The update process assumes that it does not know everything about the image, and therefore cannot make the same workaround.
