### ISSUE TITLE
Fail to COPY files from local filesystem to Docker image with imagetool

### ISSUE THREAD

**Issue by larspusa** [oracle/weblogic-image-tool#123]
Is there a way to copy external files (from local filesystem) to docker image with weblogic imagetool and/or weblogic deploying-tool.
Tries argument –additionalBuildCommands to “imagetool create” but could not get it working as only build context filesystem seem to be available.

Trying with this file for additionalBuildCommands:
[final-build-commands]
LABEL owner="TFGP middleware team"
COPY --chown=oracle:oracle documentDetails.properties /u01/domains/simple/

Output from imagetool:
ap-dbfound505t.oneadr.net: Step 51/51 : COPY --chown=oracle:oracle documentDetails.properties /u01/domains/simple/
ap-dbfound505t.oneadr.net: 
ap-dbfound505t.oneadr.net: 
[SEVERE ] Response code: -1, message: docker command failed with error: Failed to build image: COPY failed: stat /opt/apps/docker/tmp/docker-builder872733021/documentDetails.properties: no such file or directory

Imagetool seem to prepend pathname with /opt/apps/docker/tmp/docker-builder872733021/.

If this is not possible to fix what is suggested way to copy a file with imagetool or createDomain tool?

**Comment by ddsharpe** [comment]
@larspusa you need to use the --additionalBuildFiles command to copy the local files into the docker build context folder.  The command takes a comma separated list of (local) files.  The Image Tool will copy them into the context folder so that they can be used with the additonalBuildCommands option for commands like copy.  This feature is available in master ONLY, but will be included in the next release of Image Tool.

**Comment by larspusa** [comment]
Ah ok, now I see you wrote --additionalBuildFiles and not --additionalBuildCommands.
