### ISSUE TITLE
Support patch installation order

### ISSUE THREAD

**Issue by brahankv** [oracle/weblogic-image-tool#201]
Enhancement Request:
Patch installation of an interim patch fails as the bundle patch that is being installed, is the pre-requirement of the patch. Imagetool should provide an option (like --strictPatchOrder) to control the order of Patch installation - first install the bundle patches, then recommended patches and followed by the other interim patches.

**Comment by ddsharpe** [comment]
With the current code/release, all patches are placed into a folder for OPatch to install at the same time.  Since OPatch does not support patch ordering, image tool would need to run OPatch for each patch supplied to allow strict ordering.  Using UPDATE for each set of patches is a workaround, but increases the resulting image size for each subsequent run of update.  Due to the performance impact of running OPatch for each patch, strict ordering should not be the default behavior but it can be an option.
