### ISSUE TITLE
Question about 'imagetool cache addPatch' and passwords

### ISSUE THREAD

**Issue by lukasged** [oracle/weblogic-image-tool#24]
Hello,

I'm testing the `weblogic-image-tool` and noticed that I need to provide a username/password of an Oracle Support account for adding a patch to the local cache using the `imagetool cache addPatch` command.

A pair of questions:
- Is the transmission of the password secured (TLS)?
- Could it be possible to remove the step of verification of the local patch file, in order to avoid providing any Oracle Support account credentials?

**Comment by ddsharpe** [comment]
Regarding the security, the call to the Oracle server is over HTTPS in order to protect the user credential.  

It is possible to get around the validation of the patch by using the addEntry instead of the addPatch.  addEntry doesn't do any validation.  But, addPatch does a few extra things that make it easier for the user, such as get the software version that the patch is applicable to.  If you add the entry manually, you need to make sure to get the "key" to the cache correct with the exact version number.

**Comment by lukasged** [comment]
Thanks for the answer @ddsharpe 

If I understood correctly the behaviour of the release `1.0.0`, the command `imagetool cache addPatch` is now also able to skip validation if `--username` and `--password` are not provided. 

For example, here is my command and its output:
```
$ imagetool cache addPatch \
    --patchId p28186730 \
    --version 13.9.4.0.0 \
    --path ${CACHE_DIR}/${patch_opatch_zip}
[2019-06-14 15:25:37] [com.oracle.weblogic.imagetool.cli.cache.AddPatchEntry] [INFO   ] Skipping patch validation, username and password were not provided
[2019-06-14 15:25:37] [com.oracle.weblogic.imagetool.cli.cache.AddPatchEntry] [INFO   ] Added Patch entry 28186730_opatch=/tmp/weblogic-image-tool-cache/p28186730_139400_Generic.zip for wls
```

**Comment by ddsharpe** [comment]
No that is not correct.  "addEntry" does not do validation, "addPatch" does.  But as you saw from the other issue you posted, we need to revamp the patch validation or remove it.  The OPatch patch doesn't fit in the current validation model.

**Comment by lukasged** [comment]
ok, thanks

**Comment by jshum2479** [comment]
The patching code has been revamped and no longer do validation, therefore user credentials are no longer needed or valid for cache addPatch
