### ISSUE TITLE
Support for runnign imagetool update command without having to specify the model yaml file

### ISSUE THREAD

**Issue by preethignanesh** [oracle/weblogic-image-tool#245]
Currently, if we have to run the imagetool update command to create a image, we need to specify model yaml file as part of the command without which WDT fails to validate with the following error message- 
SEVERE Messages:
  1. WLSDPLY-20008: validateModel argument processing failed: validateModel failed to find a model file in archive /u01/wdt/models/archive.zip, and -model_file argument not specified

 This results in a validation error by the validator.
Can it be possible to have the command successfully execute without having to specify the model yaml file? This could be an enhancement either in the WDT or WIT

**Comment by ddsharpe** [comment]
@preethignanesh I will ping you on Slack. You do not need a model to use `update`.

**Comment by ddsharpe** [comment]
@preethignanesh I cannot reproduce this error.
I created an image with:
imagetool create --tag d:1 --wdtModel ./my_domain.yaml --wdtArchive ./my_domain.zip --wdtVariables ./my_domain1.10.properties --wdtModelOnly

And then updated it with:
imagetool update --tag d:2 --wdtArchive ./my_domain.zip  --wdtModelOnly --fromImage d:1

Since you specified the default domain type, I also tried with 
imagetool create --tag d:1 --wdtModel ./my_domain.yaml --wdtArchive ./my_domain.zip --wdtVariables ./my_domain1.10.properties --wdtModelOnly

All of these work with the latest release, 1.9.8.

**Comment by preethignanesh** [comment]
We were initially using 1.9.2 version of WDT and WIT. Currently tried on WIT 1.9.8 and WDT 1.9.9 release version and its working fine. It doesnt mandate the need of model file. So, closing the issue.
